### ISSUE TITLE
Scalar return type for mutation throws "NOT SUPPORTED"

### ISSUE THREAD

**Issue by Anunayth** [neo4j-graphql/neo4j-graphql-java#79] opened 2020-05-26 10:18 UTC
I am trying  to return a Scalar datatype (Boolean) for mutation. On doing so i am getting error message as "NOT SUPPORTED". 

Mutation :
mutation {
  deleteNode(name: "TrialNode") 
}

deleteNode is a custom query which has Boolean as return type.  On sending this mutation i am getting following stack trace 

java.lang.IllegalStateException: not supported
	at org.neo4j.graphql.Translator.toQuery(Translator.kt:91)
	at org.neo4j.graphql.Translator.translate(Translator.kt:48)
	at org.neo4j.graphql.Translator.translate$default(Translator.kt:39)
	at org.neo4j.graphql.Translator.translate(Translator.kt)
	at customClass...........

I tried to return String as well for custom query and that also threw the same error. How can i resolve this issue and get the Scalar value as return type?

**Comment by Andy2003** [comment] 2020-11-12 08:56
Resolved by #146 
Duplicate of #85

**Closed by Andy2003** 2020-11-12 08:56 UTC
