### ISSUE TITLE
Feature request: Distinguish between persistent and non-persistent types

### ISSUE THREAD

**Issue by rbramley** [neo4j-graphql/neo4j-graphql-java#232] opened 2021-06-11 10:55 UTC
Introduce a `@readonly` annotation so that the library can distinguish between persistent graph entities and read-only reference data / non-persistent synthetic types. 

The synthetic types allow for custom return types from complex queries used for aggregation or paths.
e.g. consider an aggregate query:
```
    type Query {
      "Movie aggregation for an actor"
      moviesPerYear(id1: ID): [yearlyCount] @cypher(statement: 
        """MATCH (Actor {id:id1})-[:STARRED_IN]->(m:Movie) 
           RETURN { year: m.release_year, occurrences: count(*) }""")
      ...
    }
    
    ...
    "This represents an aggregate return, rather than an entity."
    type yearlyCount @readonly {
        year: Int
        occurrences: Int
    }
```

The `@cypher` _query_ would benefit from _filtering_/_sorting_/_pagination_ augmentation. 

The `@readonly` _type_ does not require an _input_ type (or a _mutation_ if they are enabled) to be generated by the Neo4j augmented Schema Builder.

**Comment by Andy2003** [comment] 2021-06-11 11:18
You should use the `passThrough` argument of the cypher directive:

https://github.com/neo4j-graphql/neo4j-graphql-java/blob/master/core/src/test/resources/issues/gh-190-cypher-directive-with-passThrough.adoc

To be compatible with the js-versions, we should introduce an `@exclude` directive:

https://github.com/neo4j/graphql/blob/master/packages/graphql/tests/tck/tck-test-files/schema/directives/exclude.md

**Comment by rbramley** [comment] 2021-06-11 16:34
`@exclude` makes sense for API alignment.

I'm currently tied to Java 8, so would need to backport the `passThrough` commit as it was made after the Neo4j 4.2 / Java 11 update.

**Comment by Andy2003** [comment] 2021-06-12 15:50
duplicate of #185

**Closed by Andy2003** 2021-06-12 15:50 UTC
Labels: API-Alignment, duplicate
